### PR TITLE
Closes #5

### LINKED ISSUE #5: Add a search feature
Add a textbox that allows searching for a particular username. After searching, only that username should show up. 
Bonus if all usernames with the search phrase in it show up as well.
A back button should be integreated as well to return to the home view.

### PR DESCRIPTION
**Pull request by anirudhRowjee**
This commit closes Issue #5.

### CODE REVIEW

**Review by srujandeshpande — APPROVED** [review]

**Comment by srujandeshpande** [comment]
Looks good!

**Comment by srujandeshpande** [comment]
Can you remove the green color from the searched results?

**Comment by srujandeshpande** [comment]
Remove the Green color and I'll merge.

If you're willing to change the color to something that goes with the theme, might give a bit more!

**Comment by anirudhRowjee** [comment]
Sure, I'll do that.

**Comment by anirudhRowjee** [comment]
Dark Gray is fine?

**Comment by srujandeshpande** [comment]
!bounty 90

**Pull request merged**
