### PR TITLE
Added auto gh pages github

### PR DESCRIPTION
**Pull request by avinash-vk**
Check properly thanks!

### CODE REVIEW

**Comment by srujandeshpande** [comment]
@avinash-vk It's failing your own test

**Comment by avinash-vk** [comment]
> @avinash-vk It's failing your own test

LOLOL i know i know. working on it. I don't see a way to test actions locally :D
I'm working on it

**Comment by srujandeshpande** [comment]
@all-contributors please add @avinash-vk for infra

**Comment by srujandeshpande** [comment]
@all-contributors please add @avinash-vk for infra

**Comment by srujandeshpande** [comment]
@all-contributors please add @srujandeshpande for code, infra, bug, business, doc, eventOrganizing, ideas, maintenance, mentoring, question, test

**Comment by srujandeshpande** [comment]
@all-contributors please add @vatsalsinha for code

**Comment by srujandeshpande** [comment]
@all-contributors please add @sanskritip  for code, design

**Pull request closed without merging**
