### PR TITLE
reload button size and allignment fixed

### LINKED ISSUE #8: Reduce and Right/Left align the reload button
It it massive right now and does not look good. 
Also reduce the size and align the button to the left or right of the page.

### PR DESCRIPTION
**Pull request by abhishek-mishra17**
closes #8 
fixed the button size and added round edges to it

image

### CODE REVIEW

**Review by srujandeshpande — CHANGES_REQUESTED** [review]
Looks good. Can you add a margin to the bottom as well?

**Comment by abhishek-mishra17** [comment]
added the bottom margin for button

**Review by srujandeshpande — APPROVED** [review]

**Comment by srujandeshpande** [comment]
!bounty 20

**Comment by srujandeshpande** [comment]
@all-contributors please add @abhishek-pes for code

**Pull request merged**
