### PR TITLE
Fix #1

### LINKED ISSUE #1: Sort leaderboard by score

### PR DESCRIPTION
**Pull request by anirudhRowjee**
This is the commit to fix #1.

Changelog -
1. Serialized API data from an object with keys to an array of objects, making iteration easier
2. Re-wrote table data render code to accommodate for change 1
3. Added blank array dependency in useEffect() loading hook to prevent infinite re-render

### CODE REVIEW

**Review by avinash-vk — APPROVED** [review]
Looks great! Thanks for the contribution.

**Review by srujandeshpande — APPROVED** [review]
Looks good!

**Comment by srujandeshpande** [comment]
!bounty 50

**Comment by avinash-vk** [comment]
!bounty 50

**Comment by srujandeshpande** [comment]
@all-contributors please add @anirudhRowjee for code

**Pull request merged**
